### PR TITLE
Fixed incorrect password UI bug

### LINKED ISSUE #1085: Login: profile image and name disappear if you enter an incorrect password
- Enter an email login
- Note you see the profile image and name
- Enter an incorrect password
- Error message shows but profile image and name disappear

### PR DESCRIPTION
**Pull request by gsidebo**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #1085 

#### What's this PR do?
Fixes a bug where entering an incorrect password removed the greeting, profile image, and email from the password login UI

#### How should this be manually tested?
Enter a bad password using the email auth flow, make sure that the profile image/greeting/email address are all still visible

#### Any background context you want to provide?
I made several changes to JS test files that are not directly related to the bugfix. @rhysyngsun and I discovered that our tests for form submission events were not properly accounting for asynchronous requests, and that usage was preventing the testing of the action I added in this PR. It was an easy enough fix for the rest of the test cases so I went ahead and did that as part of this PR

#### Screenshots (if appropriate)
ss 2018-08-20 at 13 55 48

### CODE REVIEW

**Comment by gsidebo** [comment]
Broadly speaking, my thinking here is that the profile image, name, and email on the password page are bits of UI state, and it's a bad assumption that the auth endpoints should/will always return what we need to correctly represent the desired UI state

**Comment by pdpinch** [comment]
It looks like this needs a rebase.

File: static/js/reducers/ui.js [hunk 1]
```diff
@@ -35,6 +36,7 @@ export type UIState = {
   banner: BannerState,
   dialogs: Map<string, any>,
   dropdownMenus: Set<string>
```
Comment (rhysyngsun) [inline static/js/reducers/ui.js]: Need a comma here now.

File: static/js/reducers/ui.js [hunk 2]
```diff
@@ -49,6 +51,7 @@ export const INITIAL_UI_STATE: UIState = {
   banner:            INITIAL_BANNER_STATE,
   dialogs:           new Map(),
   dropdownMenus:     new Set()
```
Comment (rhysyngsun) [inline static/js/reducers/ui.js]: Need a comma here now

File: static/js/containers/auth/LoginPasswordPage_test.js [hunk 3]
```diff
@@ -64,20 +67,16 @@ describe("LoginPasswordPage", () => {
   ].forEach(([extraDataName, extraDataImg, email, descriptor]) => {
     it(`should render the page with correct messages when extra user data ${descriptor}`, async () => {
       const expectedProfileInfo = R.none(R.isNil)([extraDataName, extraDataImg])
```
Comment (rhysyngsun) [inline static/js/containers/auth/LoginPasswordPage_test.js]: Can be `R.none(R.isNil, [extraDataName, extraDataImg])` instead, which I think is a clearer read.

File: static/js/containers/auth/LoginPage_test.js [hunk 4]
```diff
@@ -101,17 +103,45 @@ describe("LoginPage", () => {
...
+    const testImgUrl = "http://example.com/abc.jpg"
+    const { inner, store } = await renderPage()
+
+    const { onSubmit } = inner.find("AuthEmailForm").props()
+
+    helper.postEmailLoginStub.returns(
+      Promise.resolve({
+        flow:       FLOW_LOGIN,
+        state:      STATE_SUCCESS,
+        extra_data: {
```
Comment (rhysyngsun) [inline static/js/containers/auth/LoginPage_test.js]: Take it or leave it: could simplify you code here a bit by defining `extra_data` as a `const` instead and then spreading it into your assertion at the end.

File: static/js/containers/auth/LoginPasswordPage.js [hunk 5]
```diff
@@ -102,9 +99,10 @@ const mapStateToProps = state => {
   const authFlow = getAuthFlowSelector(state)
   const partialToken = getAuthPartialTokenSelector(state)
   const formError = getFormErrorSelector(state)
-  const email = getAuthEmailSelector(state)
-  const name = getAuthNameSelector(state)
-  const profileImageUrl = getAuthProfileImageSelector(state)
+  const authUserDetail = state.ui.authUserDetail || {}
```
Comment (rhysyngsun) [inline static/js/containers/auth/LoginPasswordPage.js]: Is there a reason you moved away from selector usage here? `R.path` will return `undefined`, which is what you'll get for `name`, `email`, and `profileImageUrl` with this code too.

**Comment by rhysyngsun** [comment]
Functionality looks good

File: static/js/containers/auth/LoginPasswordPage.js (hunk 5 above)
Comment (gsidebo) [reply static/js/containers/auth/LoginPasswordPage.js]: No real reason. I'll add it

File: static/js/reducers/auth.js [hunk 6]
```diff
@@ -29,15 +29,21 @@ export const getAuthPartialTokenSelector = R.path([
...
-export const getAuthStateSelector = R.path(["auth", "data", "state"])
 export const getAuthProviderSelector = R.path(["auth", "data", "provider"])
-export const getAuthEmailSelector = R.path(["auth", "data", "email"])
 export const getFormErrorSelector = R.compose(
   R.head,
   R.pathOr([], ["auth", "data", "errors"])
 )
 export const isProcessing = R.path(["auth", "processing"])
 
+export const getAuthUiNameSelector = R.path(["ui", "authUserDetail", "name"])
```
Comment (rhysyngsun) [inline static/js/reducers/auth.js]: Could you move these to `ui.js`? they should live alongside the reducer they are for.
