### PR TITLE
Banner message if creating a post on reddit fails

### LINKED ISSUE #911: Display an error when posting to reddit fails
Currently on CI when a post to reddit fails, the user is returned to the channel listing page, without any clue of what happened. We need to return an error to the user, and also raise an exception to Sentry so we can fix the underlying problem.

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
- Closes #911

#### What's this PR do?
If anything goes wrong with creating a new post or comment on reddit, a banner message should be displayed with the text "Something went wrong creating your <post|comment>. Please try again or contact us at <support_email>"

#### How should this be manually tested?
- Temporarily add a line to `channels.models.api.Api.create_post` to make it always raise an Exception:
  ```
  raise ValueError('Fake Error')
  ```
- Go to the the post creation page, enter valid values, and submit the form.  The banner message should appear.
- Remove the modification to `Api.create_post` and resubmit the post form.  You should be redirected to the new post's detail page.

- Temporarily add a line to `channels.models.api.Api.create_comment` to make it always raise an Exception
- Go to the a post detail page, enter a comment, and submit the form.  A banner message should appear instead of a snackbar, however the detail page will also reload as an error page (see #1069).

### CODE REVIEW

**Comment by Ferdi** [comment]
Or you want to handle that in a different way ?

**Comment by mbertrand** [comment]
@Ferdi there is already code to handle an an error when posting a comment, but it uses a snackbar message instead of a banner.  I haven't changed that yet.

**Comment by aliceriot** [comment]
with respect to #1069 should we address that at the same time? if not, the functionality looks great

**Comment by mbertrand** [comment]
Peter told me that #1069 can wait til later, @pdpinch let me know if you change your mind.

File: static/js/containers/CreatePostPage.js [hunk 1]
```diff
@@ -26,6 +27,9 @@ import type {
 import type { RestState } from "../flow/restTypes"
 import type { Dispatch } from "redux"
 import type { Match } from "react-router"
+import { setBannerMessage } from "../actions/ui"
+import { clearPostError } from "../actions/post"
+import { anyErrorExcept404 } from "../util/rest"
```
Comment (aliceriot) [inline static/js/containers/CreatePostPage.js]: can you move these function imports up with the other function imports above? we typically try to sort our imports following the [style guide](https://github.com/mitodl/eslint-config#import-order)

File: static/js/containers/CreatePostPage.js [hunk 2]
```diff
@@ -127,6 +135,7 @@ class CreatePostPage extends React.Component<CreatePostPageProps> {
           key:  actions.embedly.get.requestType
         }
       }
+      // $FlowFixMe
```
Comment (aliceriot) [inline static/js/containers/CreatePostPage.js]: why was this addition necessary? just curious

File: static/js/containers/CreatePostPage.js [hunk 3]
```diff
@@ -174,9 +183,20 @@ class CreatePostPage extends React.Component<CreatePostPageProps> {
...
+        })
+        .catch(() => {
+          dispatch(
+            setBannerMessage(
+              `Something went wrong creating your post. Please try again or contact us at ${
+                SETTINGS.support_email
+              }`
+            )
+          )
+        })
```
Comment (aliceriot) [inline static/js/containers/CreatePostPage.js]: this promise handling code might be a little more readable if written with the `async / await` sugar

File: static/js/containers/CreatePostPage_test.js [hunk 4]
```diff
@@ -256,6 +258,31 @@ describe("CreatePostPage", () => {
     submitPost(wrapper)
     assert.lengthOf(wrapper.find(".channel-select .validation-message"), 0)
   })
+  //
```
Comment (aliceriot) [inline static/js/containers/CreatePostPage_test.js]: empty comment?

File: static/js/components/CommentForms.js [hunk 5]
```diff
@@ -184,17 +185,18 @@ const mapDispatchToProps = (dispatch: any, ownProps: CommentFormProps) => {
...
             )
           } else {
             // Unknown errors
             dispatch(
-              setSnackbarMessage({
-                message: "Unknown error replying to comment"
-              })
+              setBannerMessage(
+                `Something went wrong creating your comment. Please try again or contact us at ${
+                  SETTINGS.support_email
```
Comment (aliceriot) [inline static/js/components/CommentForms.js]: should we maybe do a `mailto` link here? not sure if the banner supports that

File: static/js/containers/CreatePostPage.js (hunk 2 above)
Comment (mbertrand) [reply static/js/containers/CreatePostPage.js]: With the addition of the catch block further below for posting, suddenly flow started complaining about:
```
Cannot call dispatch(...).then because property then is missing in object type [1].
```

¯\_(ツ)_/¯

Comment (aliceriot) [reply static/js/containers/CreatePostPage.js]: that's...bizarre

Comment (mbertrand) [reply static/js/containers/CreatePostPage.js]: Actually that was for the `dispatch.then` block below, which had been fine before.  For embedly the flow error was this:
```
Cannot call await with dispatch(...) bound to p because object type [1] is incompatible with Promise [
```

File: static/js/containers/CreatePostPage.js (hunk 3 above)
Comment (aliceriot) [reply static/js/containers/CreatePostPage.js]: with `async / await` you can avoid any of the promise chaining type stuff (with `.then`, `.catch`, etc) and write code that just looks synchronous. to replace `.catch` you can do

```js
try {
  const post = await dispatch(actions.posts.post(
    channelName, data
  ))
  history.push(postDetailURL(channelName, post.id, post.slug))
} catch {
  dispatch(
    setBannerMessage(
      `Something went wrong creating your post. Please try again or contact us at ${
        SETTINGS.support_email
      }`
    )
  )
}
```

this is basically equivalent to the `.catch` stuff. I find using `await` ends up generally being a lot more readable than working with raw promises.

File: static/js/components/CommentForms.js (hunk 5 above)
Comment (mbertrand) [reply static/js/components/CommentForms.js]: Gave it a try, seems like only plain text will work

**Comment by mbertrand** [comment]
@aliceriot ready for review again

File: static/js/components/CommentForms.js (hunk 5 above)
Comment (aliceriot) [reply static/js/components/CommentForms.js]: ah, we'll that's ok, sort of a 'nice to have' anyhow
