### PR TITLE
Fix field name for channel description

### LINKED ISSUE #365: Channel description is not showing up in about panel

### PR DESCRIPTION
**Pull request by noisecapella**
#### What are the relevant tickets?
Fixes #365 

#### What's this PR do?
Fixes the field used for the about page

#### How should this be manually tested?
Verify that the text shows up in the about panel

### CODE REVIEW

**Comment by noisecapella** [comment]
@aliceriot I reverted the change, this PR now just makes some minor tweaks to tests and the factory

**Comment by aliceriot** [comment]
ok, did we decide that we want the `.description` field actually?

File: static/js/components/ChannelSidebar.js [hunk 1]
```diff
@@ -1,3 +1,4 @@
+// @flow
```
Comment (aliceriot) [inline static/js/components/ChannelSidebar.js]: :scream:

File: static/js/components/ChannelSidebar_test.js [hunk 2]
```diff
@@ -13,17 +14,17 @@ describe("ChannelSidebar", () => {
   it("should render sidebar", () => {
     const channel = makeChannel()
     const wrapper = renderSidebar(channel)
-    const [description] = wrapper.find(ReactMarkdown)
-    assert.equal(description.props.source, channel.description)
+    const description = wrapper.find(ReactMarkdown)
+    assert.equal(description.props().source, channel.description)
```
Comment (aliceriot) [inline static/js/components/ChannelSidebar_test.js]: what's the reason for this change?

Comment (noisecapella) [reply static/js/components/ChannelSidebar_test.js]: Flow is unhappy with the `const [description] = wrapper.find(ReactMarkdown)` line since it doesn't think the `Wrapper` is indexable. https://github.com/facebook/flow/issues/1323

Comment (aliceriot) [reply static/js/components/ChannelSidebar_test.js]: hmmm well I suppose we can go with this, although personally I think if the code if valid then flow is wrong and the code shouldn't have to change (especially given that this is a test file, and flow is of somewhat limited value when writing tests)
