### PR TITLE
fix comment share url

### LINKED ISSUE #1216: Share url for comments does not include the hostname, just the relative url
This should have the full url

2018-09-19-135147_1920x1080_scrot

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
closes #1216 
#### What's this PR do?

this fixes the comment share url, so that it is an absolute URL and not a relative one.

#### How should this be manually tested?

check that the URL in the comment share popup is an absolute one.

### CODE REVIEW

File: static/js/lib/url.js [hunk 1]
```diff
@@ -57,11 +57,11 @@ export const embedlyResizeImage = (key: string, url: string, height: number) =>
...
 
+export const absolutizeURL = (url: string) =>
+  new URL(url, window.location.origin).toString()
+
 export const postPermalink = (post: Post): string =>
-  new URL(
-    postDetailURL(post.channel_name, post.id),
-    window.location.origin
-  ).toString()
+  absolutizeURL(postDetailURL(post.channel_name, post.id))
```
Comment (mbertrand) [inline static/js/lib/url.js]: I noticed that the post slug isn't being included but probably should be (for example, `/c/mypost/u` vs `/c/mypost/u/myslug`).  Not the same issue the PR is addressing, but wondering if it should be fixed here anyway since the line of code is being modified?

```python
absolutizeURL(postDetailURL(post.channel_name, post.id, post.slug))
```

**Comment by pdpinch** [comment]
Yeah, if it’s not too much trouble we should include the slug in the shared URL. It helps with SEO. 


> I noticed that the post slug isn't being included but probably should be (for example, /c/mypost/u vs /c/mypost/u/myslug). Not the same issue the PR is addressing, but wondering if it should be fixed here anyway since the line of code is being modified?

File: static/js/lib/url.js (hunk 1 above)
Comment (aliceriot) [reply static/js/lib/url.js]: yeah, I think that's a good idea, I'll go ahead and add it

**Comment by aliceriot** [comment]
@mbertrand I added the slug
