### PR TITLE
Fix bug unchecking lists

### LINKED ISSUE #2481: Unchecking a checked list on AddToListDialog sometimes unchecks wrong box
### Steps to Reproduce

- Make a few lists
- Check a few lists on the AddToListDialog then close
- Reopen the dialog and uncheck some of the boxes

### Expected Behavior

The resource is removed from that list and the box you clicked on is unchecked

### Actual Behavior

The resource is removed from that list and sometimes another box you didn't click on is unchecked

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #2481

#### What's this PR do?
Fixes #2481

#### How should this be manually tested?
- Make a few lists
- Check a few lists on the AddToListDialog then close
- Reopen the dialog and uncheck some of the boxes

### CODE REVIEW

**Comment by aliceriot** [comment]
ah, I ran into this issue too but thought it was just because of my slow computer!

File: static/js/components/AddToListDialog.js [hunk 1]
```diff
@@ -100,8 +100,8 @@ export default function AddToListDialog() {
     const matchingList = find(propEq("list_id", userListId), resource.lists)
     if (checked && !matchingList) {
       resource.lists.push({ list_id: userListId })
-    } else {
-      resource.lists.pop(matchingList)
+    } else if (matchingList && !checked) {
+      resource.lists.splice(resource.lists.indexOf(matchingList), 1)
     }
   }
```
Comment (aliceriot) [inline static/js/components/AddToListDialog.js]: is this `updateResource` basically just to modify the object on the frontend in order to render the right UI?

Comment (aliceriot) [reply static/js/components/AddToListDialog.js]: just wondering if there might be a better way to do this overall - i.e. if we're going to be editing the object it is probably better to that in the redux store itself rather than indirectly here

Comment (mbertrand) [reply static/js/components/AddToListDialog.js]: Yes (1st comment), maybe? (2nd) - not sure what the best way of doing that is, the userlist entitities are being modified/returned in the API calls rather than the resource being added to those lists.  If I modify `updateResource` to be something like:
```
  const [, updateResource] = useRequest(
    resource ? courseRequest(resource.id) : null
  )
```
then the dialog is closed as soon as I check or uncheck a box.

Comment (aliceriot) [reply static/js/components/AddToListDialog.js]: yeah that would fetch a new one, I don't think we need to do that but if we wanted to we could try to do a modification in the `update` method for the `userListMutation`. it's just probably not the best thing to modify the object here, but there's not an easy way to do that so I think it's probably ok
