### PR TITLE
fix Select component when removing last selection

### LINKED ISSUE #2429: Error removing last topic from a userlist
### Steps to Reproduce

Add 2+ topics to a list on the UserListDialogForm.  Remove all but one, then try to remove the last one by clicking on the 'x' for that topic.

### Expected Behavior

The topic is removed.

### Actual Behavior

The topic is not removed.  Clicking the larger X to clear the whole field will remove it though.

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #2429

#### What's this PR do?
- Lets a user remove the only topic in the topic select field.

#### How should this be manually tested?
- Add 1 topic in the UserListFormDialog
- Click the 'x' on that topic to remove it.  It should disappear.

### CODE REVIEW

File: static/js/components/Select_test.js [hunk 1]
```diff
@@ -16,29 +16,34 @@ describe("Select", function() {
...
     className = "class"
-    field = { name: "TestName" }
-    form = {}
-    options = [
-      [{ value: 1, label: "Option A" }, { value: 2, label: "Option B" }]
-    ]
+    form = {
+      setFieldValue: setFieldValueStub
+    }
+    ;(options = [
```
Comment (aliceriot) [inline static/js/components/Select_test.js]: I think there's some weird formatting stuff here, `;(` and the `( )` around the `field` assignment below
