### PR TITLE
Label course availability by model field instead of dates in UI

### LINKED ISSUE #1861: Some prior courses are missing end dates so are shown as "Available Now"
### Steps to Reproduce

Search courses with query "Advanced Introductory Classical Mechanics" - a bunch of results will return.  Most are from years past and are no longer available on MITX, but will be listed as "Available Now" because the courses have empty end dates.

### Expected Behavior
Not sure - Is it correct to assume that a course is still available if it has no end date, and this is a bad data issue?  Should end date be estimated as 4-5 months beyond the start date if missing?  

### Screenshot or Screencast
screen shot 2019-02-14 at 11 52 11 am

### LINKED ISSUE #1910: Update availability on the course detail view and search result cards
The availability shown on the course detail view and search result cards are still calculated from start and end dates, they should be changed to use the new `availability` field now that it has been added to the model.

Related to #1898

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1910
Closes #1861

#### What's this PR do?
Displays course availability based on the `Course` model's availability field, rather than start and end dates.  In particular, changes the `courseAvailability` function and renames it to `availabilityLabel`.  This function will now replace "Archived" with "Prior", "Current" with "Available Now", and display other availabilities as is.

#### How should this be manually tested?
Go to `/courses/search`.  The search results and facet choices should show these availabilities: Available Now, Prior, Upcoming, Starting Soon.  Select the 'Available Now' or 'Prior' facet and verify that they still work correctly.

### CODE REVIEW

**Comment by aliceriot** [comment]
functionality looks good!

File: static/js/factories/search.js [hunk 1]
```diff
@@ -88,7 +88,9 @@ export const makeCourseResult = (): CourseResult => ({
   instructors:       ["instuctor 1", "instructor 2"],
   topics:            [casual.word, casual.word],
   prices:            [{ mode: "audit", price: casual.number }],
-  object_type:       "course"
+  object_type:       "course",
+  availability:
+    casual.random_element[(COURSE_ARCHIVED, COURSE_CURRENT, "Upcoming")]
```
Comment (aliceriot) [inline static/js/factories/search.js]: would it make sense to declare `"Upcoming"` as a constant in `constants.js` as well?

File: static/js/lib/courses.js [hunk 2]
```diff
@@ -1,23 +1,23 @@
...
-  course.platform === platforms.OCW
-    ? COURSE_AVAILABLE_NOW
-    : moment(course.start_date).isAfter(moment())
-      ? _.capitalize(COURSE_UPCOMING)
-      : moment(course.end_date).isBefore(moment())
-        ? _.capitalize(COURSE_PRIOR)
-        : COURSE_AVAILABLE_NOW
+import type { Course } from "../flow/discussionTypes"
+
+export const availabilityLabel = (availability: ?string) => {
```
Comment (aliceriot) [inline static/js/lib/courses.js]: just a question, for similar little helper functions for the course UI we generally have the signature `Course => string`, do you think it would make sense to keep the same API here for consistency? You could add a line right below this one like

```js
const { availability } = course
```

to grab the availability value out of the course object

File: static/js/factories/search.js (hunk 1 above)
Comment (mbertrand) [reply static/js/factories/search.js]: I had thought about it, but this is just for tests, and could be anything like "blahblah" for testing purposes, so decided against it.  Happy to change it if you prefer.

File: static/js/lib/courses.js (hunk 2 above)
Comment (mbertrand) [reply static/js/lib/courses.js]: This was the original signature, but I changed it because it's now being used by `SearchFacet` as the `labelFunction`, which does not get passed the full `Course` object.

Comment (mbertrand) [reply static/js/lib/courses.js]: https://github.com/mitodl/open-discussions/pull/1922/files#diff-f3d2dc8b6c7c97d4acc6f60b8e663a61R77

Comment (aliceriot) [reply static/js/lib/courses.js]: ah ok, that makes sense

File: static/js/factories/search.js (hunk 1 above)
Comment (aliceriot) [reply static/js/factories/search.js]: not necessary, it just seemed like it was popping up in a few different places, haha
