### PR TITLE
fix a few issues with comment voting

### LINKED ISSUE #221: show spinner when updating score
We've noticed that changing a vote can be slow to update. 

As a stopgap measure we can show a spinner while the score is being updated.

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #221 (from 2017!)
partially addresses #748

#### What's this PR do?

this PR fixes a few issues with comment voting. namely:

- now instead of failing and blowing up the UI (see #748) when a comment vote fails 
- I also fixed the optimistic update behavior for the comment vote to immediately reflect what the score on the comment will be *after* the user's vote is applied.

#### How should this be manually tested?

if you have a comment on your local reddit that is older than 6 months you can use that to test this, else you can apply the following patch:

```patch
diff --git a/channels/views/comments.py b/channels/views/comments.py
index be8e5af0..d1fbfe43 100644
--- a/channels/views/comments.py
+++ b/channels/views/comments.py
@@ -209,6 +209,7 @@ class CommentDetailView(APIView):
 
     def patch(self, request, *args, **kwargs):  # pylint: disable=unused-argument
         """Update a comment"""
+        return Response(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
         with translate_praw_exceptions(request.user):
             comment = self.get_object()
             subscriptions = lookup_subscriptions_for_comments(
```

then try upvoting and downvoting comments to try out the new user experience.

also play around with upvoting and downvoting various comments *without* the 500 error to make sure the optimistic score update works as it should.

also try upvoting and downvoting comments on the profile page, that should work as expected.

#### Screenshots (if appropriate)

this is what used to happen when a comment vote failed:

Screenshot from 2020-07-16 12-32-49

this is what happens now:

Screenshot from 2020-07-16 12-33-47

so the user at least doesn't see a total error state.

### CODE REVIEW

File: static/js/components/CommentVoteForm.js [hunk 1]
```diff
@@ -55,9 +80,38 @@ export default function CommentVoteForm(props: Props) {
   const downvoted = comment.downvoted !== downvoting && !upvoting
   const upvoted = comment.upvoted !== upvoting && !downvoting
 
+  // here we create an optimistic score based on assuming that the action in
+  // progress (if any) will succeed
+  let { score } = comment
```
Comment (abeglova) [inline static/js/components/CommentVoteForm.js:85]: Can you add a check for whether the comment author is the user? Upvoting/downvoting your own comment does not affect the score. When the user votes on their own comment this causes an incorrect score to flash before reverting to the previous score

File: static/js/components/CommentVoteForm.js [hunk 2]
```diff
@@ -20,32 +22,55 @@ export default function CommentVoteForm(props: Props) {
   const [upvoting, setUpvoting] = useState(false)
   const [downvoting, setDownvoting] = useState(false)
 
+  const showErrorBanner = useCallback(
```
Comment (abeglova) [inline static/js/components/CommentVoteForm.js:25]: Should we display an error banner when upvoting posts fails as well?

Comment (aliceriot) [reply static/js/components/CommentVoteForm.js:25]: probably - but I think I'm going to tackle that in a separate PR. I'm sort of just going through all this older code in open when I have time and trying to fix it up :)

File: static/js/components/CommentVoteForm.js (hunk 1 above)
Comment (aliceriot) [reply static/js/components/CommentVoteForm.js:85]: yeah, that's a good idea, I'll add that in

**Comment by aliceriot** [comment]
@abeglova I think everything should be updated now
