### PR TITLE
Don't show suggestion if it is effectively the same as search text

### LINKED ISSUE #3286: Search suggestion is same as search term
### Steps to Reproduce

Same issue as https://github.com/mitodl/ocw-www/issues/34 - the suggestion is shown if it differs from the search term in case, or if the search term includes quotes or non-alphanumeric characters like ":" or "!".  

Search for "radiative transfer" with a topic of "Particle Physics", i.e. https://ocwnext.odl.mit.edu/search/?q=%22radiative%20transfer%22&t=Particle%20Physics

### Expected Behavior

No suggestion is shown because the suggestion is the same as the search text.

### Actual Behavior

I get the suggested search message: Did you mean "radiative transfer"?

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #3286 

#### What's this PR do?
Ignores quotes, case, and special characters when comparing a search suggestion to the search text.

#### How should this be manually tested?
Perform a search included a search term in quotes with a colon in between words, that only returns 1 result, like "Fiction: Great Books!" On https://discussions-rc.odl.mit.edu/learn/search?q=%22Fiction%3A%20Great%20Books%21%22 the suggested search term "fiction great books" will display.  On this branch, the suggested search term should not display.  Change the search term to "Fiction: Great Boos!" and it should display.

### CODE REVIEW

File: static/js/pages/CourseSearchPage.js [hunk 1]
```diff
@@ -232,7 +232,16 @@ export default function CourseSearchPage(props: Props) {
...
   const suggestions =
     !emptyOrNil(suggest) && !emptyOrNil(text)
-      ? R.without([text], suggest).map(
+      ? R.without(
+        [
+          text
+            .toLowerCase()
+            .replace(/^"(.*)"$/, "$1")
+            .replace(/[\W]+/g, " ")
+            .trim()
```
Comment (noisecapella) [inline static/js/pages/CourseSearchPage.js:241]: Can we move this before the double quote regex so we can handle ` "search phrase"` for example?

**Review by noisecapella — CHANGES_REQUESTED** [review]

File: static/js/pages/CourseSearchPage.js (hunk 1 above)
Comment (mbertrand) [reply static/js/pages/CourseSearchPage.js:241]: Thanks, looks like I need it in both places (for example, ` "aerospace: biomedical!" `

**Comment by mbertrand** [comment]
@noisecapella ready for another look

**Review by noisecapella — APPROVED** [review]
