### PR TITLE
fix issue with twitter embeds

### LINKED ISSUE #744: tweet embeds aren't working with embed.ly

### PR DESCRIPTION
**Pull request by aliceriot**
#### What are the relevant tickets?

closes #744

#### What's this PR do?

This fixes the bug with embedded tweets not showing up, but ensuring that the twitter JS is on the page and calling its little bootstrap function when necessary.

I think the issue came about because we don't put the twitter HTML on the page at page-load, but afterwards, whenever the embedly request comes back. 

#### How should this be manually tested?

Make sure that if you embed a tweet it will show up in a nice normal tweet embed sort of fashion.

### CODE REVIEW

File: static/js/containers/PostPage.js [hunk 1]
```diff
@@ -178,7 +181,14 @@ class PostPage extends React.Component<*, void> {
       ])
 
       if (post.url) {
-        await dispatch(actions.embedly.get(post.url))
+        const embedlyResponse = await dispatch(actions.embedly.get(post.url))
+
+        if (
```
Comment (mbertrand) [inline static/js/containers/PostPage.js]: This seems to be identical to code in `CreatePostPage`,  maybe it could be moved to a common function in `lib/embed.js`?

```javascript
export const loadTwitter = (embedlyResponse) => {
  if (embedlyResponse && embedlyResponse.response.provider_name === "Twitter") {
    window.twttr.widgets.load()
  }
}
```

File: static/js/factories/embedly.js [hunk 2]
```diff
@@ -27,6 +27,23 @@ export const makeImage = () => ({
   type:          "photo"
 })
 
+export const makeTweet = () => ({
+  provider_url:    "http://twitter.com",
```
Comment (mbertrand) [inline static/js/factories/embedly.js]: Should this be `https` or does it not really matter?

File: static/js/containers/PostPage.js (hunk 1 above)
Comment (aliceriot) [reply static/js/containers/PostPage.js]: yeah, that's a good idea

File: static/js/factories/embedly.js (hunk 2 above)
Comment (aliceriot) [reply static/js/factories/embedly.js]: this is just a sample response I captured from embedly, so yeah it should be https but...

in the test it's really just a placeholder so I think it's ok

**Comment by aliceriot** [comment]
@mbertrand comments addressed!
