### PR TITLE
Don't show an error page if comment posting fails

### LINKED ISSUE #1069: Don't display error page if creating a comment fails.
If posting a comment on a post detail page fails for whatever reason, the page will reload as an error page, onto which the snackbar/banner error message will appear.  Ideally the page would continue to display as is.

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
- Fixes #1069

#### What's this PR do?
- Adds a `clearCommentError` dispatch action, similar to `clearPostError`, to prevent an error page being shown after an error occurs creating a comment.

#### How should this be manually tested?
- Go to a post detail page.
- Make comment posting certain to fail by turning off the reddit vagrant box; or adding `raise Exception()` to the beginning of the `channels.api.create_comment` method.
- Reply to the post or an existing comment with a new comment and click Submit.
- An error banner should appear at the top of the page and the post page should still display correctly.
- The same should happen if you edit one of your existing comments and click Submit.

### CODE REVIEW

File: static/js/components/CommentForms.js [hunk 1]
```diff
@@ -227,9 +229,30 @@ const mapDispatchToProps = (dispatch: any, ownProps: CommentFormProps) => {
...
+            // Unknown errors
+            dispatch(
+              setBannerMessage(
+                `Something went wrong editing your comment. Please try again or contact us at ${
+                  SETTINGS.support_email
+                }`
+              )
+            )
+          }
+        }),
```
Comment (aliceriot) [inline static/js/components/CommentForms.js]: two questions about this function:

- I think it might be a little easier to read if it were written with the `async / await` sugar, up to you
- if the comment creation fails, should we also do `cancelReply` in that case, as well as in the success case? as it you see the banner message that your comment failed, but the form stays open. might prompt the user to spam submitting the comment, even if it won't ever work. what do you think?

Comment (mbertrand) [reply static/js/components/CommentForms.js]: I rewrote the patch and post functions to use async/await.  I decided to use cancelReply if the error is `410` (comment deleted) only, because another error might be a temporary issue and the user might want to try again, or at least copy their reply text before it disappears and try again later.

Comment (aliceriot) [reply static/js/components/CommentForms.js]: cool, just tried that out and it works well
