### PR TITLE
Fix 'Offered By' display

### LINKED ISSUE #2236: "Offered By" on LearningResourceCard is blank for MITx courses
### Steps to Reproduce

Load the `/courses' page.  Courses that show up in the carousels have blank "Offered By" values.

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #2236 

#### What's this PR do?
Fixes 'Offered By' subtitle on course cards.

#### How should this be manually tested?
All the cards on the courses home page should have populated 'Offered By' values.

### CODE REVIEW

File: static/js/components/LearningResourceCard_test.js [hunk 1]
```diff
@@ -91,25 +89,32 @@ describe("LearningResourceCard", () => {
...
-      assert.equal(
-        platformName.prop("content"),
-        platformReadableNames[platform]
-      )
-      assert.equal(platformName.prop("label"), "Offered by - ")
+      assert.equal(offeredBySubtitle.prop("content"), object.offered_by)
+      assert.equal(offeredBySubtitle.prop("label"), "Offered by - ")
+    })
+  })
+  //
```
Comment (aliceriot) [inline static/js/components/LearningResourceCard_test.js]: can you add a blank line above the `//` line here?
